# fly.toml app configuration file generated for emmasela-phonebook-backend on 2024-01-15T21:57:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "emmasela-phonebook-backend"
primary_region = "lhr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
